# Generated by Django 6.0.1 on 2026-03-11 10:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=api.models.photo_upload_path),
        ),
    ]
